### ISSUE TITLE
Plugin malfunction with python-2.7.5-92.el7_9

### ISSUE THREAD

**Issue by skfikus** [henrysher/cob#15]
Hello, the plugin has become malfunction with the (currently) latest python-2.7.5-92.el7_9.x86_64 in CentOS7. Could you please check it? No error is thrown by the plugin, it "just" doesn't work with static AWS credentials anymore. Thank you very much in advance for check&fix, Michal.

**Comment by paul-li** [comment]
Change [this](https://github.com/henrysher/cob/blob/40b39eb52ea58a40ae9099661088d89f9704b511/cob.py#L163) to this:

cr.append(path + ('\n' if not '\n' in path else ''))

Also, as a colleague pointed out, this [PR](https://github.com/henrysher/cob/pull/14) fixes it in the same way.

**Comment by skfikus** [comment]
Thank you very much, it did the thing!
